# .air.toml
root = "."
tmp_dir = "tmp"
[build]
  cmd = "go build -o ./tmp/main ."
  bin = "tmp/main"
  full_bin = ""
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]
  exclude_file = []
  follow_symlink = true
  exclude_regex = ["_test.go"]
[log]
  time = true
[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"
